CREATE TABLE admin_deletion_notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  pet_name VARCHAR(255),
  owner_id INT NOT NULL,
  reason TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
