CREATE TABLE pets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  age VARCHAR(50),
  species VARCHAR(100),
  breed VARCHAR(255),
  gender VARCHAR(20),
  location VARCHAR(255),
  photo VARCHAR(255),
  user_id INT NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT Available,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
